package com.example.ledger.domain;

public enum LedgerError {

    UNKNOWN_ACCOUNT,
    UNSUPPORTED_EVENT_TYPE,
    EVENT_ALREADY_EXISTS,
    EVENT_NOT_FOUND,

    REVERSAL_NOT_FOUND,
    REVERSAL_ACCOUNT_MISMATCH,
    REVERSAL_AMOUNT_MISMATCH,
    REVERSAL_VALUE_DATE_MISMATCH,
    REVERSAL_NOT_ALLOWED,

    AUTHORIZATION_NOT_FOUND,
    AUTHORIZATION_ALREADY_EXISTS,
    AUTHORIZATION_INVALID_STATE,
    AUTHORIZATION_ACCOUNT_MISMATCH,

    SETTLEMENT_NOT_ALLOWED,
    SETTLEMENT_AMOUNT_EXCEEDED,

    INSUFFICIENT_BALANCE
}

